Repository ieeeupsb/Dora, pull requests merged in 2019-07, with the labels that each got.

#23 AO3400 Symbol added to library
  pcb/rasbot.dcm
  pcb/rasbot.lib
  pcb/sym-lib-table
Labels: new symbol

#24 IR - Reviewed IR matrix #4
  pcb/infrared.sch
  pcb/infrared_matrix.sch
  pcb/infrared_row.sch
  pcb/ir.sch
  pcb/mcu.sch
  pcb/motors.sch
  pcb/rasbot-cache.lib
  pcb/rasbot.sch
  pcb/sensors.sch
Labels: enhancement

#25 IR Matrix - Missing Supply Connection
  pcb/infrared_row.sch
  pcb/ir.sch
  pcb/mcu.sch
  pcb/motors.sch
  pcb/rasbot-cache.lib
  pcb/rasbot.sch
  pcb/sensors.sch
Labels: bug

#34 STM32F4
  pcb/fp-info-cache
  pcb/infrared_row.sch
  pcb/ir.sch
  pcb/mcu.sch
  pcb/motors.sch
  pcb/rasbot-cache.lib
  pcb/rasbot.sch
  pcb/sensors.sch
Labels: enhancement

#33 Description of the project
  README.md
Labels: documentation

#29 Fixed AO3400 symbol
  pcb/rasbot.dcm
  pcb/rasbot.lib
Labels: new symbol

#37 Added BQ76925 KiCAD symbol
  pcb/rasbot.dcm
  pcb/rasbot.lib
Labels: new symbol
